### ISSUE TITLE
`revalidateLogic` does not work with React Native

### ISSUE THREAD

**Issue by RobertOstermann** [TanStack/form#1744]
### Describe the bug

Describe the bug

Not sure if this should be listed as a bug or feature request. The `revalidateLogic` function used with the `onDynamic` validator doesn't seem to work with React Native. The docs indicate that TanStack Form should work out of the box with React Native, so not sure if this is a bug or just this feature does not work for React Native.

### Your minimal, reproducible example

N/A

### Steps to reproduce

- Create a React Native project
- Add the `validationLogic: revalidateLogic()` to the `useAppForm` hook
- Attempt to run the project using React Native on an IOS simulator
- Note the error: "Uncaugh Error: (0, _classPrivateFieldLooseBase2(...)_eventTarget]().addEventListener is not a function (it is undefined)

### Expected behavior

All features in TanStack Form should work in React Native. If this is expected to not work, the [docs](https://tanstack.com/form/v1/docs/framework/react/guides/dynamic-validation) on dynamic validation should mention it.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="345" height="741" alt="Image" src="https://github.com/user-attachments/assets/99f02ce5-007d-4a88-8cd6-7134a2102476" />

### Platform

Platform
- Mac with IOS simulator

### TanStack Form adapter

react-form

### TanStack Form version

v1.21.1

### TypeScript version

v5.8.3

**Comment by DvzZDev** [comment]
Same error happens to me after upgrading to SDK 54. Any fix?
(Edit: Upgrading from 1.12.1 to 1.20.0 fixed the issue for me.)

**Comment by RobertOstermann** [comment]
Interesting, looks like `v1.20.0` is working, but `v1.21.1` is not for me. I can use `v1.20.0` in the meantime. Does `v1.21.1` also not work for you?

**Comment by patrikduksin** [comment]
+1 on 1.21.1 + expo 54

**Comment by jordankkk** [comment]
Same here (on 1.21.1) with bare react native 0.81.4, but i get ```TypeError: crypto.randomUUID is not a function (it is undefined)```, It was working on 1.20.0.

<img width="564" height="318" alt="Image" src="https://github.com/user-attachments/assets/e43fa9f9-33c6-4649-9851-4c7070314f54" />

**Comment by crutchcorn** [comment]
The bug is here:

https://github.com/TanStack/form/blob/684dec01142ceddb4b18d00dfff8aa9725a9b38d/packages/form-core/src/FormApi.ts#L1002

We need to replace this function with `uuid`'s `v4` method: http://npmjs.com/package/uuid

I'm very sick at the moment, but will forward to the team. PRs welcome in the interim

**Comment by harry-whorlow** [comment]
Hi guys, sorry for not anticipating this... I'm working on the next patch for Form Devtools (where the issue was originally created) and I'll have it fixed there. 

Should be released today!

**Comment by AlemTuzlak** [comment]
We've debugged and fixed both the mentioned issues on native, fix coming very soon!

**Comment by RobertOstermann** [comment]
Awesome, thanks for the quick responses!

**Comment by qwezey** [comment]
I updated to v1.21.2 but I am still seeing the issue. I do see that the source code for v1.21.2 has the issue fixed, but for some reason I am still getting the error after a clean install

**Comment by harry-whorlow** [comment]
Yeah, there's a conflict in the release. I'm fixing it atm

**Comment by harry-whorlow** [comment]
@qwezey, just for clarification what is the error, the event listener, or crypto

**Comment by qwezey** [comment]
@harry-whorlow the error is crypto

**Comment by harry-whorlow** [comment]
Okays awesome, I will drop a message here when the patch is deployed

**Comment by jinsley8** [comment]
> Same here (on 1.21.1) with bare react native 0.81.4, but i get `TypeError: crypto.randomUUID is not a function (it is undefined)`, It was working on 1.20.0.
> 
> <img alt="Image" width="564" height="318" src="https://private-user-images.githubusercontent.com/38534295/490920063-e43fa9f9-33c6-4649-9851-4c7070314f54.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0NzYzNjAsIm5iZiI6MTc1ODQ3NjA2MCwicGF0aCI6Ii8zODUzNDI5NS80OTA5MjAwNjMtZTQzZmE5ZjktMzNjNi00NjQ5LTk4NTEtNGM3MDcwMzE0ZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTIxVDE3MzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMmIxZDVhN2NjODA2MWFiZDY3YmIwNDk5YTUwMGRiMTE1ZjIwZjk1YmRlNDEyMDY1MjczZjFhMzZjYTA5NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M1pq0LDGO_ospfrQPF96-RsFgP-1IbdYygATLcGH3Rk">

To fix the crypto error, install `react-native-get-random-values` and import it in `/app/_layout.tsx`

**Comment by joshkeldam** [comment]
@jinsley8 can confirm this addition fixes the issue.

**Comment by harry-whorlow** [comment]
My pr should fix this issue without the polyfil... If one of you wants to be a massive help, if you could check to see if @lukeed/uuid works in an native environment, or even pull my pr branch as the version for your package.json and see if it works, I can get it merged quicker 😄 

Im pretty slammed with tasks today, so the help would be appreciated  🤘

**Comment by sivantha96** [comment]
Any update on this?

**Comment by harry-whorlow** [comment]
@sivantha96 I'll release now, there was something in devtools that needs to be patched but I think this is more pressing issue 😊

[edit] It's merged, just waiting for the release pr to be created then it will be released

**Comment by sivantha96** [comment]
@harry-whorlow nice. It works. Thanks

**Comment by harry-whorlow** [comment]
@RobertOstermann can you check it works and if so close the issue? Thanks! and sorry for the delay

**Comment by RobertOstermann** [comment]
@harry-whorlow This seems to be working, thanks!
