### ISSUE TITLE
<form.Subscribe> allows missing selector in types, but crashes at runtime (selector is not a function)

### ISSUE THREAD

**Issue by ShrJamal** [TanStack/form#2063]
### Describe the bug

`form.Subscribe` currently allows omitting `selector` at type level, but in runtime it passes `undefined` into `useStore`, which throws:

`TypeError: selector is not a function`

So there is no TypeScript warning, but the app crashes when rendering `<form.Subscribe>` without `selector`.

### Your minimal, reproducible example

https://tanstack.com/form/latest/docs/examples/react/simple

### Steps to reproduce

```tsx
const form = useForm({
  defaultValues: { name: "" },
  onSubmit: async () => {},
})

return (
  <form.Subscribe>
    {(s) => <button disabled={s.isSubmitting}>Save</button>}
  </form.Subscribe>
)
```

### Expected behavior

Either:
- selector should be optional and default internally to identity ((state) => state), or
- selector should be required in types so TS catches this at compile time.

### How often does this bug happen?

None

### Platform

macOS

### TanStack Form adapter

None

### TanStack Form version

1.28.4

### TypeScript version

5.9.3

**Comment by AdrianAndersen** [comment]
+1 to this. Seems like the issue was introduced in 1.28.4

**Comment by NBruhno** [comment]
I'm experiencing a similar issue related to the selector as well but with a selector set where I return an object which also makes the tab hang and crash on mount. Works in `v1.28.3`.

Example
```tsx
<form.Subscribe
	selector={(state) => ({
		genres: state.values.genres,
		themes: state.values.themes,
	})}
>
	{() => {
		form.handleSubmit()
		return null
	}}
</form.Subscribe>
```

Granted this use case is a bit silly with the submit 😁
