### ISSUE TITLE
After updating to v0.3.1, it is not possible to refer to it with import statement.

### ISSUE THREAD

**Issue by Toru-Takagi** [TanStack/form#458]
### Describe the bug

Since upgrading to v0.3.1, I have been getting the following error.

`Cannot find module '@tanstack/react-form' or its corresponding type declarations.ts(2307)`

I am concerned that since v0.3.1, the build directory is no longer created in the node_modules package.

If this is due to my lack of knowledge, I apologize 🙇 

## before (v0.0.15)
<img width="1650" alt="スクリーンショット 2023-09-09 15 48 36" src="https://github.com/TanStack/form/assets/17228849/740acbc2-2aec-43d8-b4da-4ea755216d5b">

## after (v0.3.1)
<img width="1643" alt="スクリーンショット 2023-09-09 15 50 17" src="https://github.com/TanStack/form/assets/17228849/dac9cc28-27c5-4a3d-869a-b531f2f1d30f">

### Your minimal, reproducible example

Described in the description

### Steps to reproduce

1. `yarn upgrade-interactive --latest`
2. versionup @tanstack/react-form v0.0.15 -> `v0.3.1`

# What else has been implemented
- delete yarn.lock and run yarn command
- yarn install --immutable --immutable-cache --check-cache

### Expected behavior

Correct import status

### How often does this bug happen?

Every time

### Platform

- OS: Mac
- Node: v18.17.1
- @tanstack/react-form: ^0.3.1
- next: 13.4.16
- react: 18.2.0
- typescript: ^5.1.6

### Tanstack Form adapter

None

### TanStack Form version

v0.3.1

### TypeScript version

v5.1.6

**Comment by crutchcorn** [comment]
This is a known issue. Something's wrong with our CI system and it's quite frustrating overall.

We'll figure it out soon. Will ping when resolved. 

For now, suggested to use 0.2.x

**Comment by Toru-Takagi** [comment]
>This is a known issue.

My apologies 🙇 
Use v0.2.x.

**Comment by crutchcorn** [comment]
No no, you're awesome for reporting this - I just happened to be in the middle of trying to fix this. Not frustrated with you - frustrated with our CI/CD system 😅😅 Really sorry if I came across as short.

This _should_ be fixed in `0.3.2`, can you confirm for us? :)

**Comment by crutchcorn** [comment]
Closing as I've validated this has been fixed. Heads up @Toru-Takagi you'll want to use the brand newly published `0.3.4` as it includes important fixes to the `error` array
